In [37]:
# Downscailing images, try1, try2... is original pictures
# tran11, tran12... is downscaled 8 times(d = 8) with lambda = 1
# tran1, tran2... is downscaled 4 times(d = 4) with lambda = 0.5

import cv2
import numpy as np
import math
import os
import pandas as pd

### Downloading image
img = cv2.imread("try1.jpg")
d = 4
width = int(img.shape[1] / d)
height = int(img.shape[0] / d)
dim = (width, height)
print(dim)

# resize image with box_filter getting I_d picture
resized = cv2.resize(img, dim, interpolation=cv2.INTER_LINEAR)

## Kernel of the convolution
conv_kern = np.array([[1 / (16), 2 / (16), 1 / (16)],
                [2 / (16), 4 / (16), 2 / (16)],
                [1 / (16), 2 / (16), 1 / (16)]])

# opencv convolution 
res = cv2.filter2D(resized, -1, conv_kern)
res1 = cv2.filter2D(resized, -1, conv_kern)
cv2.imwrite('tran.jpg',res)
# res is I~ picture, res1 will be the final


v_max = (3 * 255 * 255) ** (0.5)
lmb = 0.5
print(1)
for i in range(height):
    for j in range(width):
        k = 0
        summ = 0
        for i1 in range(i * d, (i + 1) * d):
            for j1 in range(j * d, (j + 1) * d):
                mod = (abs((int(img[i1, j1][0]) - int(res[i, j][0]))) + abs((int(img[i1, j1][1]) - int(res[i, j][1]))) + abs((int(img[i1, j1][2]) - int(res[i, j][2]))))
                kf = (mod / v_max) ** lmb
                k += kf
                summ += img[i1, j1] * kf
        summ = (summ[0] / k, summ[1] / k, summ[2] / k)
        res1[i, j] = summ
print(res1)
cv2.imwrite('tran1.jpg',res1)

(1920, 1080)
1


<ipython-input-37-32e64bbb904c>:46: RuntimeWarning: invalid value encountered in double_scalars
  summ = (summ[0] / k, summ[1] / k, summ[2] / k)


[[[ 66  61  57]
  [  6   8  11]
  [ 52  67  73]
  ...
  [116  88  54]
  [116  88  56]
  [ 86  69  64]]

 [[115 109 100]
  [  8  10  11]
  [  7   9  13]
  ...
  [116  88  54]
  [117  89  56]
  [100  80  63]]

 [[137 134 124]
  [ 42  40  39]
  [  3   5   6]
  ...
  [117  89  55]
  [116  88  56]
  [ 83  69  61]]

 ...

 [[ 56  55  55]
  [139 141 132]
  [158 151 137]
  ...
  [163 142 110]
  [162 141 107]
  [163 141 106]]

 [[ 18  15  16]
  [ 57  56  54]
  [154 148 137]
  ...
  [162 141 109]
  [163 142 109]
  [163 141 106]]

 [[ 13  12  10]
  [ 25  22  22]
  [111 108 102]
  ...
  [166 147 116]
  [166 145 114]
  [164 144 111]]]


True